apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::052937454741:role/eksctl-user16-cluster-nodegroup-NodeInstanceRole-13H7XRSV0OOBZ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-02T06:04:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "930"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c0e6530d-1327-4c2b-908b-cf9c765effea
